### ISSUE TITLE
No active absorbing molecules

### ISSUE THREAD

**Issue by wj198414** [ucl-exoplanets/TauREx3_public#4]
I got the following issue when I tried the quickstart example. Any ideas?

I set up folders like this:
[Global]
xsec_path = "/Users/wang.12220/Documents/py_packages/taurex_data/xsec/"
cia_path = "/Users/wang.12220/Documents/py_packages/taurex_data/cia/"

and got the following messages:

taurex -i quickstart.par --plot
taurex - INFO - TauREx 3.0.3-beta
taurex - INFO - TauREx PROGRAM START AT 2020-06-19 11:13:21.749318
taurex.ParamParser - INFO - Interpolation mode set to linear
taurex.ParamParser - WARNING - Xsecs will be loaded in memory
taurex.ParamParser - WARNING - Radis is disabled
taurex.ParamParser - WARNING - Radis default grid will be used
taurex.TransmissionModel - INFO - Building model........
taurex.TransmissionModel - INFO - Collecting paramters
taurex.TransmissionModel - INFO - Setting up profiles
taurex.TransmissionModel - INFO - Computing pressure profile
taurex.ChemistryModel - INFO - Initializing chemistry model
taurex.ChemistryModel - INFO - Initializing chemistry model
taurex.TransmissionModel - INFO - Setting up contributions
taurex.TransmissionModel - INFO - DONE
taurex.TransmissionModel - ERROR - No active molecules detected
taurex.TransmissionModel - ERROR - Most likely no cross-sections were detected
Traceback (most recent call last):
  File "/Users/wang.12220/opt/anaconda3/bin/taurex", line 8, in <module>
    sys.exit(main())
  File "/Users/wang.12220/opt/anaconda3/lib/python3.6/site-packages/taurex/taurex.py", line 96, in main
    wngrid = model.nativeWavenumberGrid
  File "/Users/wang.12220/opt/anaconda3/lib/python3.6/site-packages/taurex/model/simplemodel.py", line 356, in nativeWavenumberGrid
    raise InvalidModelException('No active absorbing molecules')
taurex.exceptions.InvalidModelException: No active absorbing molecules

**Comment by ahmed-f-alrefaie** [comment]
Does the `/Users/wang.12220/Documents/py_packages/taurex_data/xsec` folder contain the actual pickle files or are they in another folder inside that directory? The xsec_path filed must point to a directory with pickle/hdf5 files in the root of the directory. Using the dropbox files in the documentation you would need to do something like /Users/wang.12220/Documents/py_packages/taurex_data/xsec/xsec_sampled_R15000_0.3-15

This also applies to the cia path argument

Let me know if it works!

**Comment by wj198414** [comment]
It works, here what I am using:
[Global]
xsec_path = "/Users/wang.12220/Documents/py_packages/taurex_data/xsec/xsec_sampled_R15000_0.3-15"
cia_path = "/Users/wang.12220/Documents/py_packages/taurex_data/cia/HITRAN"

**Comment by wj198414** [comment]
Thanks.

Ji

**Comment by ahmed-f-alrefaie** [comment]
No worries! I will close this
