### ISSUE TITLE
Citations of dependencies

### ISSUE THREAD

**Issue by JohannesBuchner** [ucl-exoplanets/TauREx3_public#8]
Dear all,

Would it be possible to add a reminder in https://taurex3-public.readthedocs.io/en/latest/citation.html to cite all the packages used. I see you have a nice list already in https://taurex3-public.readthedocs.io/en/latest/user/installation.html#dependencies with the links.

I am asking because I just saw a paper citing multinest and TauREx, but not pymultinest, and I would appreciate the citation as it was a lot of work to develop.

Cheers,
Johannes

**Comment by ahmed-f-alrefaie** [comment]
Hi Johannes

I've updated the citation page, you can find the commit here: 0a5555c19ce13947a9617ad9ee4911780222a6a6

I've referenced the A&A publication.
Many apologies for this, we appreciate the work you've done, the library has been extremely useful for us! I'm glad you caught this, I can add this reference to our papers.

Let me know if it's okay with you and I can close the issue.

Regards,

Ahmed

**Comment by JohannesBuchner** [comment]
Great, thanks!
